### ISSUE TITLE
Accessing admin Panel

### ISSUE THREAD

**Issue by Edouard-Legoupil** [allendecid/AIchat#2]
Hi - first congrat for the project - it matches what I was looking for -
How can I access the admin panel displayed here: http://www.onl.cl/AIchat/admin/index.html - 

Thanks

**Comment by allendecid** [comment]
Hi Edouard. The project is old on built on obsolete technologies. It is not a good idea to continue it. If you want you can get an non-commercial license at ChatCompose. Use the contact section to get one.

**Comment by Edouard-Legoupil** [comment]
Thanks -  the idea of a pure JS bot remains quite good - actually I already started testing chatcompose - are you working there?
